### ISSUE TITLE
Issue with Active Directory "Display name" and comma

### ISSUE THREAD

**Issue by mleblanc136** [pluginsGLPI/moreldap#10]
Hi, I have trouble with the synchronisation of the "physicalDeliveryOfficeName" between Active Directory and GLPI 0.90.1. The problem is that if the "Display name" of a user in AD contains a comma, then it will not sync the location. Unfortunately, in my case, the display names are as follow "Lastname, Firstname".

2016-01-25 16:58:21
  **\* PHP Warning(2): ldap_read(): Search: Invalid DN syntax
  Backtrace :
  :
  plugins/moreldap/hook.php:91                       ldap_read()
  :                                                  plugin_moreldap_item_add_or_update_user()
  inc/plugin.class.php:1095                          call_user_func()
  inc/commondbtm.class.php:1118                      Plugin::doHook()
  inc/authldap.class.php:2088                        CommonDBTM->update()
  inc/user.class.php:2501                            AuthLDAP::ldapImportUserByServerId()
  inc/massiveaction.class.php:991                    User::processMassiveActionsForOneItemtype()
  inc/massiveaction.class.php:970                    MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()

What can I do to make it work?

Thank you!
(Vous pouvez m'écrire en français, je suis francophone!)

**Comment by dethegeek** [comment]
Hi

I did a quick fix. Can you try it ? 

https://github.com/pluginsGLPI/moreldap/archive/patch-issue-10.zip

**Comment by mleblanc136** [comment]
Hi,

I tried the fix, but it doesn't work. Same as before but now, removing the comma does not work either.

Thanks!

**Comment by dethegeek** [comment]
Thank you. 

I can reproduce the issue. I'm investigating to find a fix. Not sure yet if the bug is in the plugin or GLPI itself.

**Comment by dethegeek** [comment]
Hi

Download again the zip linked above. This is a workaround, and it appears to be working for me.

**Comment by mleblanc136** [comment]
Hi,

It seems to be working perfectly! 

Nice work and thank you for the fast respond!
