### ISSUE TITLE
Hi Friend! GLPI 0.90.1 Compatibility

### ISSUE THREAD

**Issue by estebanruizrios** [pluginsGLPI/moreldap#11]
My name is Esteban and I´m new in this GLPI thing, and I (we GLPI admins) find your plugin is very helpfull,  I aprecciate if can can tell me.. it´ll have GLPI 0.90.1 compatibility?

**Comment by dethegeek** [comment]
Hi

Try the master branch

**Comment by estebanruizrios** [comment]
sorry... i didn't get it

**Comment by Megachip** [comment]
@estebanruizrios the [latest version](https://github.com/pluginsGLPI/moreldap/releases/tag/0.90-0.2.2) works fine with 0.90.X branch.
