### ISSUE TITLE
Installation improvement suggestion

### ISSUE THREAD

**Issue by Armin83** [pluginsGLPI/moreldap#15]
After extract the plugin folder is named glpi not moreldap.
I moved it from ...plugin/glpi to ...plugin/moreldap should this work?
If it is named glpi it does not appear in plugin list but know it does not work or i do something wrong.

I have to investigate more time.

It should be similar to the other plugins.

**Comment by btry** [comment]
Hi

You did right by renaming the folder to **moreldap** as you described. Once the plugin appears in GLPi, it is ready to activate and use.

**Comment by trasher** [comment]
Hello,

Thanks for your report. This have been fixed on the just released `0.2.3` of the plugin.
