### ISSUE TITLE
Edit LDAP username in GLPI

### ISSUE THREAD

**Issue by tyronewyatt** [pluginsGLPI/moreldap#16]
Could you offer an option to edit LDAP usernames in your GLPI plugin?
So I use active directory for LDAP in my sites and import users into GLPI.
Every now and again users usernames change. 
This generally happens if someone gets married/divorced. 
We are unable to change LDAP usernames in GLPI directly so we have to edit them using PHPmyAdmin.

**Comment by btry** [comment]
Hi

I understand your need, but GLPi uses the LDAP resource for reading only, then I thought the plugin should behave this way too, when I created it.

Are you aware GLPi is able to sync LDAP imported accounts ? This should solve your need.

**Comment by btry** [comment]
Hi

No feedback, closing.
