### ISSUE TITLE
mysql error

### ISSUE THREAD

**Issue by Stoatwblr** [pluginsGLPI/moreldap#2]
bug against 0.85.5

When installing from the current master.zip

  **\* MySQL query error:
  SQL: ALTER TABLE `glpi_plugin_moreldap_authldaps`
             ADD COLUMN `entities_id` INT(11) NOT NULL default  \'0\',
               ADD COLUMN `is_recursive` INT(1) NOT NULL DEFAULT \'0\'
  Error: Duplicate column name 'entities_id'
  Backtrace :
  plugins/moreldap/hook.php:51  
  inc/plugin.class.php:639                           plugin_moreldap_install()
  front/plugin.form.php:45                           Plugin->install()

You might want to look at http://blog.geekq.net/2010/08/11/add-column-safely-mysql/ as it shows how to check if a table already exists.

**Comment by btry** [comment]
Hi

A single line was missing, launching install and upgrade process. That's why you got this error. It has been fixed
