### ISSUE TITLE
GLPI 0.90 Support

### ISSUE THREAD

**Issue by Megachip** [pluginsGLPI/moreldap#4]
;) 

THX a lot.

**Comment by Manu1400** [comment]
You could use last commit version of this plugin.

**Comment by neeftarah** [comment]
Hi,
The 2.0 version should work with GLPI 0.90 with a single line change.

This change have been done in commit 79a814f and next version will be fully compatible with GLPI 0.90.

You can do the change done in the commit or wait for the next version that should come fast now.

Best regards,
Jérémy
