### ISSUE TITLE
Installation SQL error | GLPI 0.84 - MoreLDAP 0.1-bugfixes

### ISSUE THREAD

**Issue by neeftarah** [pluginsGLPI/moreldap#5]
2015-12-09 15:55:17
**\* MySQL query error: 

---

SQL: ALTER TABLE `glpi_plugin_moreldap_authldaps`
             ADD COLUMN `entities_id` INT(11) NOT NULL default  \'0\',
           ADD COLUMN `is_recursive` INT(1) NOT NULL DEFAULT \'0\'
Error: Duplicate column name 'entities_id'
Backtrace :
/var/www/html/00-GLPI/glpi_084/plugins/moreldap/hook.php&nbsp;:51       DBmysql->query()
/var/www/html/00-GLPI/glpi_084/inc/plugin.class.php&nbsp;:615       plugin_moreldap_install()
/var/www/html/00-GLPI/glpi_084/front/plugin.form.php&nbsp;:45       Plugin->install()
/var/www/html/00-GLPI/glpi_084/front/plugin.form.php

I think this is due to a lack of "break;" line in the "case" hook.php:46

**Comment by dethegeek** [comment]
Seems to be duplicate of #2 . 

should be already fixed

**Comment by neeftarah** [comment]
Maybe the same, but for 0.84 version (#2 is for 0.85).
I use last github version (0.1-bugfixes) and  is not fixed for this version. But maybe only a cherry-pick ?

**Comment by dethegeek** [comment]
A cherry pick should be sufficient. 

By the way, I think the installation code of the plugin should  be rewritten to use the Migration class. It is far more maintainable than the current implementation. Sooner is better for this kind of work. I'll create a ticket for this.

**Comment by neeftarah** [comment]
Fixed by commit 766f2893
