### ISSUE TITLE
User locations not translated  | GLPI 0.84 - MoreLDAP 0.1-bugfixes 

### ISSUE THREAD

**Issue by neeftarah** [pluginsGLPI/moreldap#6]
Strings not translated (I use French) : 
![moreldap-translations](https://cloud.githubusercontent.com/assets/6593470/11688759/c2f0e2a0-9e8e-11e5-9dab-8c31620c8f6c.png)

**Comment by dethegeek** [comment]
Translations not yet done.

**Comment by neeftarah** [comment]
Translations added by commit 6d1b4e94 :
- French
- English
- Russian
- Turkish
